import { Product } from "./types";

export const products: Product[] = [
  {
    id: "p1",
    slug: "deep-maroon-silk-saree-gold-border",
    name: "Deep Maroon Silk Saree with Gold Zari Border",
    category: "sarees",
    images: ["/brand/photos/hero-saree.jpg", "/brand/photos/hero-wedding.jpg"],
    price: 2399,
    discountedPrice: 1899,
    description:
      "A rich maroon silk-blend saree with a traditional gold zari border, designed to drape beautifully for weddings, pujas, and festive gatherings. Comes with a matching unstitched blouse piece.",
    colors: ["Maroon", "Deep Red"],
    sizes: [],
    stock: 8,
    stockStatus: "in-stock",
    sku: "TV-SAR-001",
    isBestSeller: true,
    rating: 4.8,
    reviewCount: 24,
    reviews: [
      { id: "r1", customerName: "Priya R.", rating: 5, comment: "Gorgeous drape and the zari work is stunning in person!", date: "2026-08-02" },
      { id: "r2", customerName: "Meena S.", rating: 4.5, comment: "Beautiful saree, blouse piece fabric is lovely too.", date: "2026-07-18" },
    ],
    tags: ["silk saree", "wedding saree", "zari border", "festive"],
    fabric: "Silk blend",
    fit: "6.3m with blouse piece",
    careInstructions: "Dry clean only",
    occasions: ["Weddings", "Festivals", "Formal events"],
  },
  {
    id: "p2",
    slug: "blush-pink-silk-saree-festive",
    name: "Blush Pink Silk Saree — Festive Edit",
    category: "sarees",
    images: ["/brand/photos/pink-saree.jpg"],
    price: 2199,
    discountedPrice: 1799,
    description:
      "A soft blush pink silk saree with delicate gold detailing along the border — elegant enough for a wedding, gentle enough for daytime festivities.",
    colors: ["Blush Pink"],
    sizes: [],
    stock: 5,
    stockStatus: "in-stock",
    sku: "TV-SAR-002",
    isNewArrival: true,
    rating: 4.6,
    reviewCount: 11,
    reviews: [{ id: "r3", customerName: "Anjali K.", rating: 5, comment: "So elegant, got many compliments!", date: "2026-08-20" }],
    tags: ["silk saree", "blush saree", "festive"],
    fabric: "Silk blend",
    fit: "6.3m with blouse piece",
    careInstructions: "Dry clean only",
    occasions: ["Weddings", "Daytime functions"],
  },
  {
    id: "p3",
    slug: "blush-pink-floral-cotton-kurti",
    name: "Blush Pink Floral Print Cotton Kurti",
    category: "kurtis",
    images: ["/brand/photos/pink-kurti.jpg"],
    price: 899,
    discountedPrice: 699,
    description:
      "A breathable 100% cotton kurti in soft blush pink with a delicate floral print — effortless enough for daily wear, pretty enough for a casual outing.",
    colors: ["Blush Pink", "Ivory"],
    sizes: ["S", "M", "L", "XL", "XXL"],
    stock: 22,
    stockStatus: "in-stock",
    sku: "TV-KUR-001",
    isBestSeller: true,
    rating: 4.7,
    reviewCount: 38,
    reviews: [
      { id: "r4", customerName: "Divya M.", rating: 5, comment: "Super comfortable for daily wear!", date: "2026-08-15" },
      { id: "r5", customerName: "Kavya T.", rating: 4.5, comment: "True to size, lovely fabric.", date: "2026-07-30" },
    ],
    tags: ["cotton kurti", "floral kurti", "daily wear"],
    fabric: "100% Cotton",
    fit: "Straight fit",
    careInstructions: "Machine washable",
    occasions: ["Daily wear", "Casual outings", "Office (with a jacket)"],
  },
  {
    id: "p4",
    slug: "sage-green-straight-kurti",
    name: "Sage Green Straight-Fit Kurti",
    category: "kurtis",
    images: ["/products/kurti-sage-1.jpg", "/products/kurti-sage-2.jpg"],
    price: 949,
    discountedPrice: 749,
    description: "A calm sage green kurti in soft cotton — an easy everyday layer that pairs beautifully with our thread bangles.",
    colors: ["Sage Green"],
    sizes: ["S", "M", "L", "XL"],
    stock: 15,
    stockStatus: "in-stock",
    sku: "TV-KUR-002",
    isNewArrival: true,
    rating: 4.5,
    reviewCount: 9,
    reviews: [],
    tags: ["cotton kurti", "sage kurti", "everyday ethnic"],
    fabric: "Cotton",
    fit: "Straight fit",
    careInstructions: "Machine washable",
    occasions: ["Daily wear", "Casual outings"],
  },
  {
    id: "p5",
    slug: "maroon-embroidered-festive-kurti",
    name: "Maroon Embroidered Festive Kurti",
    category: "kurtis",
    images: ["/brand/photos/hero-suit.jpg"],
    price: 1299,
    discountedPrice: 999,
    description: "Rich maroon kurti with fine gold-thread embroidery on the neckline — festive-ready with everyday comfort.",
    colors: ["Maroon"],
    sizes: ["S", "M", "L", "XL", "XXL"],
    stock: 3,
    stockStatus: "low-stock",
    sku: "TV-KUR-003",
    isBestSeller: true,
    rating: 4.9,
    reviewCount: 17,
    reviews: [{ id: "r6", customerName: "Sneha P.", rating: 5, comment: "Wore this for Diwali, felt beautiful!", date: "2026-09-01" }],
    tags: ["embroidered kurti", "festive kurti", "maroon"],
    fabric: "Cotton-silk blend",
    fit: "A-line",
    careInstructions: "Dry clean recommended",
    occasions: ["Festivals", "Family functions"],
  },
  {
    id: "p6",
    slug: "cotton-dress-material-unstitched-set",
    name: "Cotton Dress Material — Unstitched Set",
    category: "dress-materials",
    images: ["/brand/photos/fabric-stack.jpg"],
    price: 1099,
    discountedPrice: 849,
    description: "A 3-piece unstitched cotton dress material set — top fabric, bottom fabric, and dupatta — ready for your tailor.",
    colors: ["Gold", "Maroon"],
    sizes: ["Unstitched"],
    stock: 12,
    stockStatus: "in-stock",
    sku: "TV-DM-001",
    rating: 4.4,
    reviewCount: 6,
    reviews: [],
    tags: ["dress material", "unstitched suit", "cotton"],
    fabric: "Pure cotton",
    fit: "Unstitched — 2.5m top, 2.5m bottom, 2.25m dupatta",
    careInstructions: "Hand wash recommended for first wash",
    occasions: ["Custom tailoring", "Everyday ethnic"],
  },
  {
    id: "p7",
    slug: "maroon-gold-thread-bangle-set",
    name: "Maroon & Gold Handwoven Bangle Set",
    category: "thread-bangles",
    images: ["/brand/photos/bangles.jpg"],
    price: 329,
    discountedPrice: 249,
    description:
      "Twelve bangles, hand-knotted in rich maroon and gold thread, made to catch the light with every move of your wrist. A Traditional Vastraa favorite for festive mornings and everyday elegance alike.",
    colors: ["Maroon & Gold"],
    sizes: ["2.4in", "2.6in", "2.8in"],
    stock: 30,
    stockStatus: "in-stock",
    sku: "TV-BNG-001",
    isBestSeller: true,
    rating: 4.9,
    reviewCount: 52,
    reviews: [
      { id: "r7", customerName: "Ritu A.", rating: 5, comment: "Absolutely beautiful, handmade quality shows!", date: "2026-08-28" },
      { id: "r8", customerName: "Lakshmi V.", rating: 5, comment: "Ordered a second set as a gift.", date: "2026-08-10" },
    ],
    tags: ["thread bangles", "handmade bangles", "maroon gold bangle set"],
    bangleSize: "2.4in – 2.8in (adjustable fit)",
    bangleCount: 12,
    material: "Hand-knotted cotton thread with metallic accents",
    occasions: ["Festivals", "Weddings", "Everyday ethnic wear"],
  },
  {
    id: "p8",
    slug: "blush-gold-thread-bangle-set",
    name: "Blush & Gold Handwoven Bangle Set",
    category: "thread-bangles",
    images: ["/brand/photos/bangles.jpg"],
    price: 289,
    discountedPrice: 229,
    description: "A soft blush-and-gold 10-piece bangle set — delicate, feminine, and easy to pair with pastel outfits.",
    colors: ["Blush & Gold"],
    sizes: ["2.4in", "2.6in", "2.8in"],
    stock: 26,
    stockStatus: "in-stock",
    sku: "TV-BNG-002",
    isNewArrival: true,
    rating: 4.8,
    reviewCount: 19,
    reviews: [],
    tags: ["thread bangles", "blush bangle set", "handmade"],
    bangleSize: "2.4in – 2.8in (adjustable fit)",
    bangleCount: 10,
    material: "Hand-knotted cotton thread",
    occasions: ["Everyday wear", "Gifting", "Casual festive"],
  },
  {
    id: "p9",
    slug: "sage-cream-thread-bangle-set",
    name: "Sage & Cream Handwoven Bangle Set",
    category: "thread-bangles",
    images: ["/brand/photos/bangles.jpg"],
    price: 259,
    discountedPrice: 199,
    description: "An earthy sage-and-cream 8-piece bangle set, perfect for a fresh, everyday look.",
    colors: ["Sage & Cream"],
    sizes: ["2.4in", "2.6in"],
    stock: 4,
    stockStatus: "low-stock",
    sku: "TV-BNG-003",
    rating: 4.6,
    reviewCount: 8,
    reviews: [],
    tags: ["thread bangles", "sage bangle set"],
    bangleSize: "2.4in – 2.6in",
    bangleCount: 8,
    material: "Hand-knotted cotton thread",
    occasions: ["Everyday wear"],
  },
  {
    id: "p10",
    slug: "festive-3-piece-kurti-set",
    name: "Festive 3-Piece Kurti Set — Maroon & Gold",
    category: "festive-combos",
    images: ["/brand/photos/hero-suit.jpg", "/brand/photos/hero-wedding.jpg"],
    price: 1899,
    discountedPrice: 1499,
    description:
      "A complete festive-ready outfit — kurti, palazzo, and dupatta in coordinated maroon and gold — so you can look put-together without piecing an outfit together yourself.",
    colors: ["Maroon & Gold"],
    sizes: ["S", "M", "L", "XL"],
    stock: 9,
    stockStatus: "in-stock",
    sku: "TV-CMB-001",
    isBestSeller: true,
    rating: 4.9,
    reviewCount: 21,
    reviews: [{ id: "r9", customerName: "Farah S.", rating: 5, comment: "Perfect for Diwali, fits beautifully.", date: "2026-09-03" }],
    tags: ["festive set", "3 piece suit", "Diwali outfit"],
    fabric: "Cotton-silk blend with zari-detailed dupatta",
    fit: "Comfortable palazzo fit",
    careInstructions: "Dry clean recommended",
    occasions: ["Festivals", "Family functions", "Diwali/Pongal gatherings"],
  },
  {
    id: "p11",
    slug: "kurti-bangle-combo-blush",
    name: "Kurti & Handmade Bangle Set Combo",
    category: "festive-combos",
    images: ["/brand/photos/pink-kurti.jpg", "/brand/photos/bangles.jpg"],
    price: 999,
    discountedPrice: 849,
    description:
      "Our blush pink kurti paired with a hand-matched thread bangle set — styled together so you don't have to guess what goes with what.",
    colors: ["Blush Pink"],
    sizes: ["S", "M", "L", "XL"],
    stock: 14,
    stockStatus: "in-stock",
    sku: "TV-CMB-002",
    isNewArrival: true,
    rating: 4.8,
    reviewCount: 13,
    reviews: [],
    tags: ["combo offer", "kurti bangle combo", "gift set"],
    fabric: "Cotton kurti + hand-knotted thread bangle set",
    fit: "Straight fit kurti, adjustable bangles",
    careInstructions: "Machine washable kurti; handle bangles gently",
    occasions: ["Gifting", "Festive wear", "Everyday styling upgrade"],
  },
  {
    id: "p12",
    slug: "premium-banarasi-soft-silk-saree",
    name: "Premium Banarasi Soft Silk Saree",
    category: "sarees",
    images: [
      "/products/saree-banarasi-peach-1.png",
      "/products/pose3.png"
    ],
    price: 3699,
    discountedPrice: 3299,
    description:
      "This beautiful Banarasi soft silk saree is crafted with intricate woven paisley and floral designs that reflect timeless tradition. The rich golden zari border with a contrast black edge adds a royal touch, making it perfect for weddings, festivals and special occasions.",
    colors: ["Peach / Rose Gold with Black Border"],
    sizes: [],
    stock: 10,
    stockStatus: "in-stock",
    sku: "TV-SAR-003",
    isNewArrival: true,
    rating: 4.9,
    reviewCount: 0,
    reviews: [],
    tags: ["banarasi saree", "soft silk saree", "zari border", "wedding saree", "festive"],
    fabric: "Soft Silk (Banarasi weave)",
    fit: "5.5 meters (approx.) with 0.8 meter blouse (Black with Gold Border)",
    careInstructions: "Dry clean only",
    occasions: ["Wedding", "Festive", "Party", "Traditional"],
  },
];

export function getAllProducts() {
  return products;
}

export function getProductBySlug(slug: string) {
  return products.find((p) => p.slug === slug);
}

export function getProductsByCategory(category: string) {
  return products.filter((p) => p.category === category);
}

export function getBestSellers() {
  return products.filter((p) => p.isBestSeller);
}

export function getNewArrivals() {
  return products.filter((p) => p.isNewArrival);
}

export function getRelatedProducts(product: Product, limit = 4) {
  return products
    .filter((p) => p.id !== product.id && p.category === product.category)
    .slice(0, limit);
}

export function searchProducts(query: string) {
  const q = query.toLowerCase();
  return products.filter(
    (p) =>
      p.name.toLowerCase().includes(q) ||
      p.tags.some((t) => t.toLowerCase().includes(q)) ||
      p.category.includes(q)
  );
}

export const categoryMeta: Record<
  string,
  { label: string; image: string; href: string }
> = {
  sarees: { label: "Sarees", image: "/brand/photos/hero-saree.jpg", href: "/shop/clothing?type=sarees" },
  kurtis: { label: "Kurtis", image: "/brand/photos/pink-kurti.jpg", href: "/shop/clothing?type=kurtis" },
  "dress-materials": { label: "Dress Materials", image: "/brand/photos/fabric-stack.jpg", href: "/shop/clothing?type=dress-materials" },
  "thread-bangles": { label: "Thread Bangles", image: "/brand/photos/bangles.jpg", href: "/shop/thread-bangles" },
  "festive-combos": { label: "Combo Offers", image: "/brand/photos/wedding-couple.jpg", href: "/shop?type=festive-combos" },
};
